name: azampaytanzania
description: "Flutter SDK for AzamPesa Tanzania mobile money integration."
version: 0.0.1
homepage: "dssd"
repository: https://github.com/yourusername/azampesa_tanzania 

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

