name: azampaytanzania
description: "Flutter SDK for AzamPesa Tanzania mobile money integration."
version: 0.0.2
homepage: "https://github.com/PhilipMuze/AzamPay-Tanzania-Flutter"
repository: https://github.com/PhilipMuze/AzamPay-Tanzania-Flutter

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0




